version: "3.8"
services:
  web:
    build:
      context: .
    image: "hosted-cbc-backend:local"
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: "hosted-db"
    ports:
      - "5412:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
