# Generated by Django 4.2.5 on 2023-09-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.CharField(default='ADD NOTES HERE', max_length=128),
        ),
    ]
